title: "CS 112 Intro to CS II"
subtitle: "CS 112-03 &bullet; Fall 2020"

name: "EJ Jung"
timezone: "America/San_Francisco"

repository: "usf-cs112-fall2020/usf-cs112-fall2020.github.io"
github: [metadata]

kramdown:
  auto_ids: true

include: ["favicon.ico"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

permalink: /guides/:title:output_ext

collections:
  general:
    title: "General Guides"
    output: true
    permalink: /guides/:collection/:name:output_ext

  eclipse:
    title: "Eclipse Guides"
    output: true
    permalink: /guides/:collection/:name:output_ext

  homework:
    title: "Homework Guides"
    output: true
    permalink: /guides/:collection/:name:output_ext

  projects:
    title: "Project Guides"
    output: true
    permalink: /guides/:collection/:name:output_ext

description: >-
   Students will learn how to program in Java and also learn how to design and implement an intermediate-size program using Object-Oriented Design.
links:
   piazza: "https://piazza.com/usfca/fall2020/cs11203/home"
   canvas: "https://usfca.instructure.com/courses/1596103"
   github: "https://github.com/usf-cs212-fall2020"

   zoom:
     - name: "CS 112-03 Lecture"
       link: "https://usfca.zoom.us/j/95724358940?pwd=aW5RenlZOW1tZWRCUHF4RlhjSXFXQT09"

     - name: "Office Hours"
       link: "https://usfca.zoom.us/j/4154225422"

     - name: "TA Office Hours"
       link: ""
